### ISSUE TITLE
coredump generated when test modify_if interface

### ISSUE THREAD

**Issue by mingfireyu** [etcd-cpp-apiv3/etcd-cpp-apiv3#181]
```C
#define WITH_GRPC_CHANNEL_CLASS
#include "etcd/Client.hpp"
#include "etcd/KeepAlive.hpp"
#include "etcd/Response.hpp"
#include "etcd/SyncClient.hpp"
#include "etcd/Value.hpp"
#include "etcd/Watcher.hpp"
#include <iostream>
#include <vector>
#include <grpc++/grpc++.h>

#include <grpc++/security/credentials.h>
//valgrind --tool=memcheck ./a.out --leak-check=full --track-origins=yes

using namespace std;

int main(int argc, char **argv) {  
  vector<etcd::Client*> etcds;

  etcds.push_back(new etcd::Client("http://10.10.4.168:2379"));
  etcds.push_back(new etcd::Client("http://10.10.4.84:2379"));
  etcds.push_back(new etcd::Client("http://10.10.4.85:2379"));
  std::string key = "test_round_robin";
  std::string value = "test_test";
    
  for (int i = 0 ; i < etcds.size(); i++){
    etcds[i]->set_grpc_timeout(std::chrono::seconds(5));
  }

  for(int i = 0 ; i < 3 ; i++){
    auto modify_if_task = etcds[0]->modify_if(key, value, value, 5);
    auto resp = modify_if_task.get();
    if (resp.is_ok()){
        std::cout<<"modify if "<<i<<resp.value().as_string()<<std::endl;
    }else {
        std::cout<<"modify if error code and message"<<resp.error_code()<<" "<<resp.error_message()<<std::endl;
    }
  }            
 
  for(int i = 0 ; i < etcds.size() ; i++){
     delete etcds[i];
  }
  std::cout<<"end main"<<std::endl;
 
  return 0;
}    
```
the call stack is :
```
0x00007ffff7a93d72 in std::_Sp_counted_ptr_inplace<pplx::details::_Task_impl<unsigned char>, std::allocator<pplx::details::_Task_impl<unsigned char> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /home/ec2-user/workspace/vendors_etcd_update/precompiled_libs/cpprest/lib/libcpprest.so.2.10
Missing separate debuginfos, use: debuginfo-install libgcc-4.8.5-44.el7.x86_64 libstdc++-4.8.5-44.el7.x86_64
(gdb) where
#0  0x00007ffff7a93d72 in std::_Sp_counted_ptr_inplace<pplx::details::_Task_impl<unsigned char>, std::allocator<pplx::details::_Task_impl<unsigned char> >, (__gnu_cxx::_Lock_policy)2>::_M_dispose() () from /home/ec2-user/workspace/vendors_etcd_update/precompiled_libs/cpprest/lib/libcpprest.so.2.10
#1  0x00007ffff769a6a8 in pplx::task<etcd::Response>::_ContinuationTaskHandle<etcd::Response, void, pplx::details::_Task_impl_base::_AsyncInit<etcd::Response, etcd::Response>(pplx::details::_Task_ptr<etcd::Response>::_Type const&, pplx::task<etcd::Response> const&)::{lambda(pplx::task<etcd::Response>)#1}, std::integral_constant<bool, true>, pplx::details::_TypeSelectorNoAsync>::~_ContinuationTaskHandle() () from ./libetcd-cpp-api.so
#2  0x00007ffff7b00401 in boost::asio::detail::completion_handler<boost::_bi::bind_t<void, void (*)(void*), boost::_bi::list1<boost::_bi::value<void*> > > >::do_complete(void*, boost::asio::detail::scheduler_operation*, boost::system::error_code const&, unsigned long) ()
   from /home/ec2-user/workspace/vendors_etcd_update/precompiled_libs/cpprest/lib/libcpprest.so.2.10
#3  0x00007ffff7aff311 in boost::asio::detail::scheduler::run(boost::system::error_code&) ()
   from /home/ec2-user/workspace/vendors_etcd_update/precompiled_libs/cpprest/lib/libcpprest.so.2.10
#4  0x00007ffff7afcae6 in (anonymous namespace)::threadpool_impl::thread_start(void*) ()
   from /home/ec2-user/workspace/vendors_etcd_update/precompiled_libs/cpprest/lib/libcpprest.so.2.10
#5  0x00007ffff7346ea5 in start_thread () from /lib64/libpthread.so.0
#6  0x00007ffff63b4b0d in clone () from /lib64/libc.so.6
```

My cpprest vesion is 2.10, grpc version is 1.41.0,  boost version is 1.68, etcd-cpp-api version is v0.2.9

Please help to check it.

**Comment by mingfireyu** [comment]
sorry, it's my environment problem, please ignore

**Comment by mingfireyu** [comment]
@sighingnow 
Sorry, if I compile lib-etcd-cpp-api.so with g++ 4.8, no coredump will generate. But if I compile lib-etcd-cpp-api.so with g++ 8 and more, the coredump will generated. It's very strange.

**Comment by mingfireyu** [comment]
please compile cpprest, grpc, lib-etcd-cpp-api.so with same gcc version
